### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by datatalking** [sakhnevych/calendar-view#15]
@sakhnevych How could we add a prioritized task list field so that we can see the items we need to put on the calendar.

If you can give me a few pointers and accept a PR I could submit a change, in addition I've been working on an intelligent scheduler that I might be able to integrate using your CalendarView. =)

**Comment by sakhnevych** [comment]
Hi @datatalking. Sure, I can help with this feature and would really appreciate your input into this library.

Can you please add more details about the feature? Do you need a field `priority` in the Event entity? If the tasks are overridden, we should draw the one with the higher priority? Or to draw events with priority 3 or higher, for example?

**Comment by sakhnevych** [comment]
I haven't received a message from you in this thread, so I'm closing the ticket.

Please feel free to reopen it or create a new one. I will be happy to help or support you with the new feature you suggested.

**Comment by datatalking** [comment]
@sakhnevych Getting back to you on this and funny enough the delay is part and parcel connected to my goal for this app is to see how much of it I can synchronize up with my task-scheduler script which works but its headless. So I'm exploring the idea for your app as daily dashboard or output of sorts for an intelligent scheduler run as needed.

Once its scheduled it texts me my schedule for the day, ideally I'm also adding a feature to have it actually schedule the times, integrate with an online scheduler manager etc.

Depending upon contraits.
1. If user wanted to manually schedule they could use app as is and generate scheduled PNG
2. If user wanted the app to schedule the events, this app would be 'intelligent' enough to guess where and when to schedule it based on prior events.

- [ ] 1. User would be prompted for task name, task start date or task finish date, estimated time to complete and other data.
- [ ] 2. This data can be in a csv file or I have a script that prompts them for it.
- [ ] 3. Then based on input it also asks for user schedule for time blocking out sleep, existing tasks etc
- [ ] 4. It ingests the csv file and computes a task list bounded by the constraints of availability.
- [ ] 5. Now I also have an algorithm I'm researching to include heuristic suggestion feedback based on the keywords and prior scheduling it makes and educated guess or suggests changes.

**Comment by sakhnevych** [comment]
@datatalking , your idea sounds interesting. I hope this library will help to build it.

If you want to add some features here, I would be happy to help.
My goal is to keep it simple and compatible with the Unix principle of "make each program do one thing well". So it will be great to have the intelligence feature in another library. Anything else in line with this principle is welcome.

**Comment by datatalking** [comment]
I have made progress on refactoring some code to align with your Unix principle of "make each program do one thing well" and wanted to discuss this. Maybe this belongs in the discussions section of GitHub but I would appreciate feedback on this.

Depending upon constraints.

 1. Once per hour/day a cron job is run to check a folder for changes to `user_schedule.csv` where the user enters 0 for not available or 1 for available.
 2. The user is prompted for task_criteria input in (48) 30-minute blocks per day.
 3. `task_criteria = project#,Task name,Importance score (1-5),Time to finish,Num of blocks,Due Date,Date Added(today)`
 4. Each block is 30 minutes which we could change to 15 minutes but this significantly increases complexity of the calculations.
sample `task_criteria`
```
project#,Task name,Important score (1-5),Time to finish,Num of blocks,Due Date,Date Added(today)
Proj_MATH384,Complete math homework,4,60,2,100923
Proj_PHYS433,Study for the Physics quiz,5,120,4,100923
``` 
 5. Using time blocking, `task_criteria` parameters are evaluated with [PULP](https://pypi.org/project/PuLP/) package to look at `user_schedule.csv` for open blocks of time and schedules tasks based on `task_criteria` and poof your schedule is updated.
 6. google calendar also has an API that would allow scheduling so your iPhone or google calendar is updated.

Current output schedules the following tasks
<img width="345" alt="Screen Shot 2023-10-05 at 3 09 02 PM" src="https://github.com/sakhnevych/calendar-view/assets/11813209/90233be1-74e3-4df5-9940-9844be8c338c">

The graphic still needs work but its one of 48 different time blocks.
<img width="812" alt="Screen Shot 2023-10-05 at 3 09 26 PM" src="https://github.com/sakhnevych/calendar-view/assets/11813209/3b18f122-ae88-428d-bfa1-81e92ef352ea">
