### ISSUE TITLE
problem with python version < 3.9

### ISSUE THREAD

**Issue by mister-pog** [sakhnevych/calendar-view#19]
support for annotation like

> def strip_lines(input_lines: list[str], strip_lines: bool) -> list[str]

was added in 3.9 (https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)

in older versions it should look like

> from typing import List

> def strip_lines(input_lines: List[str], strip_lines: bool) -> List[str]

Thus with older versions of python we have errors like

> calendar_view/core/utils.py", line 14, in StringUtils
> def strip_lines(input_lines: list[str], strip_lines: bool) -> list[str]:
> TypeError: 'type' object is not subscriptable

**Comment by sakhnevych** [comment]
Thank you for the fix, @mister-pog.

`v2.3.1` is released
