### ISSUE TITLE
Cannot import 'Literal'

### ISSUE THREAD

**Issue by datatalking** [sakhnevych/calendar-view#25]

**Comment by datatalking** [comment]
When loading the last sample code listed in your [README.md](https://github.com/sakhnevych/calendar-view) I'm getting an error that usually comes up with python 3.8 and above but I'm not as familiar with its use in calendar-view.

The `setup.py` indicates this is for python 3.6 and above but I didn't see a tox.ini file so there was no version checking when I loaded this.

"ImportError: cannot import name 'Literal' from 'typing' (/Users/user_name/opt/anaconda3/envs/Task-scheduler-problem/lib/python3.7/typing.py)"

Sample Code I used

```
from calendar_view.calendar import Calendar
from calendar_view.config import style
from calendar_view.core import data
from calendar_view.core.event import Event

style.hour_height = 80
style.event_notes_color = '#7F7F7F'

config = data.CalendarConfig(
    lang='en',
    title='Massage. Antonio',
    dates='2022-06-20 - 2022-06-24',
    show_year=True,
    mode='working_hours',
    title_vertical_align='top'
)
events = [
    Event(day='2022-06-20', start='11:00', end='12:00', title='Jesse Tyson'),
    Event(day='2022-06-20', start='12:30', end='14:00', title='Karry', notes='No music'),
    Event(day='2022-06-20', start='15:00', end='17:00', title='Taylor Davis',
          notes='Ask about the shin that hurts last time.'),
    Event(day='2022-06-20', start='17:30', end='18:30', title='Jose Hope'),

    Event(day='2022-06-22', start='10:00', end='12:00', title='Annabell Moore',
          notes='A therapist for her mother:\n+4487498375 Nick Adams'),
    Event(day='2022-06-22', start='12:30', end='14:00', title='Carlos Cassidy'),
    Event(day='2022-06-22', start='15:00', end='17:00', title='Joe'),
    Event(day='2022-06-22', start='17:30', end='18:30', title='Jose Hope'),

    Event(day='2022-06-23', start='10:00', end='11:00', title='Elena Miller'),
    Event(day='2022-06-23', start='11:30', end='13:30', title='Karry', notes='No music'),
    Event(day='2022-06-23', start='15:00', end='16:30', title='Mia Williams'),
    Event(day='2022-06-23', start='17:00', end='18:00', title='Xander'),
]

calendar = Calendar.build(config)
calendar.add_events(events)
calendar.save("massage.png")
```



Perhaps I'm implementing it wrong?

If you let me know how I can fix it I'd like to submit a PR if you are open to adding a collaborator.

**Comment by sakhnevych** [comment]
Hi @datatalking . Thank you for opening the issue.

I cannot reproduce the bug on Python 3.8.17. Please see the attached screenshot.
<img width="328" alt="Screenshot 2023-10-08 at 22 15 57" src="https://github.com/sakhnevych/calendar-view/assets/2226541/dafc4348-425f-45e8-ad45-a19bb3536e3f">

Can you please provide more details or try starting the project from scratch?
The "Literal" is not part of the calendar-view package. The bug is most probably not related to this package.

**Comment by sakhnevych** [comment]
As far as I know, `tox.ini` is a virtual environment file. I didn't add this to the project, because it is not part of the application. And I used to use `venv` for virtual environments.

```shell
python -m venv .venv
```

**Comment by sakhnevych** [comment]
Yes, I am open to collaborating. Please, create the pull request with the fix and I will be happy to see it in the next release.
