### ISSUE TITLE
Updating old code

### ISSUE THREAD

**Issue by datatalking** [sakhnevych/calendar-view#26]
I have a gist created for a splash of code that I'm trying to fix or replace and it references your CalendarView but I need help finding the source, or how to update it.

'https://gist.github.com/datatalking/a743ac9ff29dad6cbc3f8a90feb7d2b6' are you familiar with this  usage of what appears to be an older version of your code ?

**Comment by sakhnevych** [comment]
Hi @datatalking ,

I can see 3 rows with the calendar-view code:

```python
import CalendarView

calendar = CalendarView(months=1)
calendar.add_events(events)
st.write(calendar.render())
```

Please have a look at the examples in the `example` folder. They may give you an idea of how to use it.

Here are a few things to consider in the code you provide:
1. Wrong import statement.
2. The Calendar constructor gets config as a parameter
```python
    def __init__(self, config: CalendarConfig):
        ...
```
3. The library doesn't support rendering to a stream. It needs additional code improvements. If you want to add a feature, please create a pull request. Or I can do it.
