### ISSUE TITLE
Log messages go directly to root logger

### ISSUE THREAD

**Issue by abirke** [sakhnevych/calendar-view#28]
@sakhnevych, this is a nice project, thanks!

Currently, all log messages are written to the root logger directly. I believe module-specific logger classes are more or less standard to make log levels more easily configurable, prevent extensive log output and so on.

Would you be okay with me implementing the change? (Basically creating log objects for the three affected modules, and write to the module-level `logger = logging.getLogger(__name__)` instead of `logging.warning`, `logging.debug`, ...)

**Comment by sakhnevych** [comment]
Hi @abirke. I appreciate your feedback.

It sounds like a good idea. I would be happy to review and apply your MR if you have time or do the changes myself tomorrow.
